apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: APP_NAME-secrets
  namespace: prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore

  target:
    name: APP_NAME-secrets
    creationPolicy: Owner

  dataFrom:
    - extract:
        key: prod/APP_NAME

  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: shared/postgres
        property: url
