apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: APP_NAME-secrets
  namespace: qa
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore

  target:
    name: APP_NAME-secrets
    creationPolicy: Owner

  # Secrets espec√≠ficos del ambiente QA
  dataFrom:
    - extract:
        key: qa/APP_NAME

  # Secret de DB compartido
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: shared/postgres
        property: url
